AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Backend for the Prayer Request App

Parameters:
  env:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod

Resources:

  AuthService:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/services/auth
      Handler: app.handler
      Runtime: nodejs16.x
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:*
              Resource: !GetAtt UsersTable.Arn
      Environment:
        Variables:
          USERSTABLENAME: !Ref UsersTable
      Events:
        Others:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: ANY
        Base:
          Type: HttpApi
          Properties:
            Path: /
            Method: ANY
      MemorySize: 128
      Timeout: 60

  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${env}-prayer-request-app-users"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: userName
          AttributeType: S
        - AttributeName: email
          AttributeType: S
        - AttributeName: sub
          AttributeType: S
      KeySchema:
        - AttributeName: email
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: UserNameIndex
          KeySchema:
            - AttributeName: userName
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: SubIndex
          KeySchema:
            - AttributeName: sub
              KeyType: HASH
          Projection:
            ProjectionType: ALL

  FrontEndBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${env}-prayer-request-app"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        IndexDocument: index.html

  FrontEndBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontEndBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Join ["", ["arn:aws:s3:::", !Ref FrontEndBucket, "/*"]]

  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub "${env}-prayer-request-app"
      DeletionProtection: "ACTIVE"
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireNumbers: true
      AdminCreateUserConfig:
        UnusedAccountValidityDays: 7
      MfaConfiguration: "OFF"
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: verified_email
            Priority: 1
      Schema:
        - Name: email
          Required: true
          Mutable: true
      VerificationMessageTemplate:
        DefaultEmailOption: CONFIRM_WITH_LINK

  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub "${env}-prayer-request-app"
      UserPoolId: !Ref CognitoUserPool
      GenerateSecret: false

  CognitoUserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: !Sub "${env}-prayer-request-app-domain"
      UserPoolId: !Ref CognitoUserPool
